name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build PDF files
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            tickets.tex
            tasks.tex
          latexmk_shell_escape: true
          extra_system_packages: gnuplot

      - name: Gather build artifacts
        if: always()
        run: |
          mkdir -p build
          mv *.pdf ./build/ || true
          find . -name "*.log" -exec mv '{}' "./build/" ";";

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Contents
          path: build/
          retention-days: 60
          if-no-files-found: error

      - name: Prepare to publish
        if: success() && github.ref == 'refs/heads/master'
        run: |
          mkdir -p public
          cp build/*.pdf public/
          cp .github/pages.md public/README.md
          (echo; cat TODO.md) >> public/README.md

      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
