name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build PDF files
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            tickets.tex
            tasks.tex
          latexmk_shell_escape: true

      - name: Gather build artifacts
        run: |
          mkdir -p build
          mv *.pdf build/
          cp .github/pages.md build/README.md
          (echo; cat TODO.md) >> build/README.md

      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Tickets
          path: build/*.pdf
          retention-days: 60
          if-no-files-found: error

      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
