name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions: read-all|write-all

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build PDF
        uses: dante-ev/latex-action@latest
        with:
          compiler: pdflatex
          root_file: tickets.tex
          args: |
            -shell-escape
            -synctex=1
            -interaction=nonstopmode
          extra_system_packages: |
            texlive-latex-base
            texlive-lang-cyrillic
            texlive-latex-recommended

      - name: Gather build artifacts
        run: |
          mkdir -p build
          mv *.pdf build/
          cp -r README.md build/

      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Tickets
          path: build/tickets.pdf
          retention-days: 60
          if-no-files-found: error

      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
